name: Metrics
on:
  # Schedule updates (every 12 hours)
  schedule: [{cron: "0 */12 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing to main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: jtmuller5
          template: classic
          base: header, activity, community, repositories, metadata
          # Isometric Calendar (3D view)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # Achievements (Medals/Badges)
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          # Languages (Detailed)
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_indepth: yes
